### PR TITLE
Add screenshots

### PR DESCRIPTION
**Pull request by sdziuda**

### CODE REVIEW

**Comment by quozl** [comment]
* we usually try for aspect ratio of 4:3, at a resolution of 1024 or 1200 pixels wide,
* the screenshots metadata key is (a) useless for AppStream clients without other AppStream keys also added, (b) probably not needed by aslo-v3 (please check),
* the file names should end in `png` not `PNG`.

**Comment by sdziuda** [comment]
I was changing the file according to this file: https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/master/src/sugar3/bundle/__init__.py

**Comment by quozl** [comment]
Thanks.

* [x] the files are still named `.PNG` instead of `.png`, please rename them, `git mv`,
* [ ] the description has two typos, and is the same as the summary; you can find more things to say from `README.md`,
* [x] you edited the screenshots; the moon is squashed, and the writing is blurry; instead you should use a virtual machine and set the display resolution of the virtual window to 1024x768 (one of the VESA sizes), then capture the screenshot.
* [x] you made many separate commits instead of one, causing many GitHub mail notifications to be sent to everyone subscribed to Sugar Labs notifications, probably because you used the GitHub editor, which is best used with private projects; please learn to use git command line tools.

**Review by vipulgupta2048 — CHANGES_REQUESTED** [review]
Thanks @quozl and @sdziuda, 
I agree with @quozl here, the sole purpose of screenshots is for the user to see how an activity looks before installing it in their Sugar. This also helps us to check if the activity actually runs.
It would be great, if you could rename them according to the convention given that is `1.png`, `2.png` and so on.  
Also, yes I think the `metadata_license` tag can be removed.

**Comment by quozl** [comment]
Good progress, checkboxes have been ticked in earlier review, please proceed with other changes.  Also;

* [x] my understanding, and it is possible I'm wrong, is that screenshots are language dependent, so should be in `screenshots/en` if they are English, and that's how the majority of our activities are done,

**Comment by quozl** [comment]
Thanks.

* [ ] the description still has at least two typos, try a spell checker; and says almost as much as the summary; you can find more things to say from `README.md`,
* [ ] the description HTML is inconsistently indented, https://github.com/sugarlabs/moon-activity/blob/2d85f3b084a6a8f531aecf2f0fcc28baac2be218/activity/activity.info,
* [ ] a mandatory _metadata_license_ key is missing.

**Pull request merged**
