### PR TITLE
Port to JavaScript

### LINKED ISSUE #7: Port to GTK+ 3
Moon is dependent on GTK+ 2 API and must be ported to GTK+ 3 API.

_(Should anybody take this, please look at my [work in progress](https://github.com/quozl/moon-activity/tree/gtk3).  Remaining changes are the Cairo drawing.)_

### PR DESCRIPTION
**Pull request by quozl**
We've waited a very long time for a port to GTK+ 3.

This alternative pull request fixes https://github.com/sugarlabs/moon-activity/issues/7 by porting to JavaScript instead of GTK+ 3.

Changes:

- port from Python to JavaScript (by @zhirzh Shirsh Zibbu),

- change from GPLv2+ to Apache-2.0 license (by @zhirzh Shirsh Zibbu),

Problems:

- most translations lost; only {en,es,fr} are implemented; needs a translation team to bring forward any matching strings from the previous version,

- bundle inexplicably includes a generated locale/ directory; probably a Sugar Toolkit problem,

- tested on Ubuntu 18.04 with Sugar 0.112; works fine except for save image button, which does nothing.

References:

* https://github.com/llaske/sugarizer/tree/master/activities/Moon.activity
* https://github.com/zhirzh/sugarizer-activity-moon

### CODE REVIEW

**Comment by chimosky** [comment]
@quozl I think this should be merged in a separate branch, we don't want to lose the py version of this activity.

**Comment by quozl** [comment]
@chimosky, I don't understand how you could lose it.  Git will always keep it in the hash before this one, and in the v18 release tag.  Older bundle version will continue to be available for download from any site that hosts it.  Why would you ever need the Python GTK+ 2 version again?

**Comment by chimosky** [comment]
We don't need the Python GTK+ 2 version, i was thinking if eventually this activity is ported to GTK+ 3 instead of it being on top of the port to JS they'll both be separate, although this has a downside of maintenance but look on the bright side, we'll have two languages of the same activity. I also think it's a question of what language are we looking at in the future, if an activity takes this long to be ported to GTK+3 should we resort to porting it to another language?.

I get this error when i run the activity
```
File "/usr/bin/sugar-activity", line 219, in <module>
    main()
  File "/usr/bin/sugar-activity", line 127, in main
    activity_class = bundle.get_command().split(" ")[1]
IndexError: list index out of range
```

**Comment by quozl** [comment]
There's no reason to accept a port to GTK+ 3 if the port to JavaScript works well enough; and as we don't have a port to GTK+ 3 at all yet, your question is speculative.  The language is immaterial; what matters is the function and user experience of the activity.

Your error is because you ran the activity from Terminal using the Python wrapper, when you can see from the `activity.info` file `exec` key that you should have used the JavaScript wrapper.

If you'd like to improve that error message, you might add a test to the Python wrapper to handle the exception by checking for `exec` key specifying a web activity, and print a more useful message.

https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/master/bin/sugar-activity#L127

something like

```python
try:
    activity_class = bundle.get_command().split(" ")[1]
except IndexError, e:
    if bundle.get_command().startswith('sugar-activity-web'):
        print('this is not a Python activity')
    raise e
```

But it doesn't seem worth it, since end users are not expected to run activities from Terminal.

**Comment by quozl** [comment]
Rebased after _master_ changed.

**Comment by chimosky** [comment]
When activity is run it returns this error 
```
File "/usr/lib/python2.7/site-packages/sugar3/activity/webactivity.py", line 100, in _realize_cb
    xid = window.get_window().get_xid()
AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sugar3/activity/webactivity.py", line 110, in _loading_changed_cb
    key = os.environ["SUGAR_APISOCKET_KEY"]
  File "/usr/lib64/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SUGAR_APISOCKET_KEY'
```
But running with `GDK_BACKEND=x11 sugar-activity-web` - a workaround - opens the activity and nothing comes up until either `Toggle Grid View` or `Toggle Hemisphere View` is clicked but this is error is shown 
```
  File "/usr/lib/python2.7/site-packages/sugar3/activity/webactivity.py", line 110, in _loading_changed_cb
    key = os.environ["SUGAR_APISOCKET_KEY"]
  File "/usr/lib64/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SUGAR_APISOCKET_KEY'
```

**Comment by quozl** [comment]
Neither of those things happen for me when I test on Ubuntu 18.04 with Sugar 0.112.  What operating system and Sugar are you using?  Are you running the activity from the Sugar activity ring?

First error shows you are running under Wayland.  Sugar doesn't support Wayland yet.  It isn't something that will block this pull request.  If you want to work on that, see https://github.com/sugarlabs/sugar/issues/778.

SUGAR_APISOCKET_KEY is an environment variable set by Sugar, and then used by the activity via the toolkit.  If it isn't set, please find out why.  This too will not block this pull request unless you can show it is a problem with this activity alone.  There are other web activities you can test.  Gears is one example.

**Comment by chimosky** [comment]
> What operating system and Sugar are you using? 

I'm using Fedora 28 and Sugar 0.112

> Are you running the activity from the Sugar activity ring?

No.

**Comment by quozl** [comment]
> Fedora 28

Okay, I'm not using that at the moment, you may need to get more help from Fedora community, especially if the Gears activity does the same thing.

> > Are you running the activity from the Sugar activity ring?
> No.

Please do.  That's how learners are expected to use an activity.

**Comment by chimosky** [comment]
>  you may need to get more help from Fedora community, especially if the Gears activity does the same thing.

It's like you mentioned Sugar doesn't support Wayland yet, these errors don't surface in `Gnome on Xorg` since Sugar supports x11.

> Please do. That's how learners are expected to use an activity.

I will.

**Comment by quozl** [comment]
Please reproduce on other web activities and take these two problems to the https://github.com/sugarlabs/sugar-toolkit-gtk3 repository.  As far as I can see, it has nothing to do with this activity, and is just noise here.

**Pull request merged**
